
public class CoreJava1 {
	
	public static void main(String[]args) {
		//autogenerated method stub
		int myNum = 5;
		String website = "Wikipedie";
		char letter = 'r';
		double dec = 5.99;
		boolean myCard = true;
		
		System.out.println(myNum + " is the value stored in the myNum variable");
		System.out.println(website);
		
		//arrays
	//	int[] arr = new int[5];
	//	arr[0] = 10;
	//	arr[1] = 11;
	//	arr[2] = 12;
	//	arr[3] = 13;
	//	arr[4] = 14;
		
		int[] arr2 = {10,11,12,13,14,444,1000};
		System.out.println(arr2[4]);
		
		//for loop arr.lenght - 5
//		for(int i = 0; i< arr.length; i++)
//		{
//			System.out.println(arr[i]);
//		}
		
		for (int i = 0;i<arr2.length; i++)
		{
			System.out.println(arr2[i]);
		}
		
		
		String[] name = {"Ziv", "Nos", "Xxx"};
		
		for(int i = 0; i<name.length;i++)
		{
			System.out.println(name[i]);
		}
		for(String s: name)
		{
			System.out.println(s);
		}
}
}